In [17]:
import pandas as pd
import os
import json

In [3]:
!ls | grep .json

abc kopi susu.json
djarum super.json
gudang garam filter.json
indomie ayam special.json
indomie kaldu ayam.json
indomie kari ayam.json
indomie soto mie.json
kapal api kopi bubuk.json
sampoerna a mild.json
torabika duo.json

In [29]:
workdir = os.getcwd()
data_folder = open(workdir + '/' + "list_sku.txt", 'r')
Lines = data_folder.readlines()

ls_sku = []

for line in Lines:
    ls_sku.append(line.replace('\n',''))

In [30]:
ls_sku

['sampoerna a mild',
 'gudang garam filter',
 'djarum super',
 'indomie kaldu ayam',
 'indomie kari ayam',
 'indomie ayam special',
 'indomie soto mie',
 'kapal api kopi bubuk',
 'abc kopi susu',
 'torabika duo']

In [18]:
json_dict = {}
for sku in ls_sku:
    with open(workdir + "/{sku}.json".format(sku=sku), 'r') as f:
        json_dict[sku] = json.load(f)

In [40]:
json_dict['sampoerna a mild']

{'sampoerna a mild': ['0iumangs8dz4yj765wop.jpeg',
  '1byg08l5v39d4hrj7ike.jpg',
  '2a9stjoqmzkpfxcdyge3.jpg',
  '2gunsd6vjr8xfi4tble9.jpeg',
  '2y4ugp036ra9dl1q5o7z.jpeg',
  '3lpa84fyndo206mktw95.jpg',
  '3mx29udt8zfsjkqgiyne.jpg',
  '3v8l09jqcakusn5w1fi2.png',
  '5ue2wvsy98j7ixkc4lf1.jpg',
  '5zvs4j6unx9bmycprdl0.jpeg',
  '6hqwerlzb18y2tj4icos.jpeg',
  '6slnj4e8h0xfrwmv79yd.jpg',
  '7gj2xpqznwme63ik1vbt.jpg',
  '7j6mfoe1htapis5wu0zc.jpg',
  '7pu9861cbndowj3ylgmf.jpeg',
  '8pw50lj1irdyxk73sqtg.jpeg',
  '8qsiv7c9ejzrfotk31hp.jpg',
  '35d08j6t7kpczwbsahvn.jpg',
  '38sgyxv9jm0td1wcka6h.jpg',
  '40hlkitp8r679zbvqcju.jpeg',
  '62erxda5si7c1mvy4zhl.jpg',
  '87uxcogks625ywat9hr3.jpeg',
  'a2zgd91oi7ejqxmh8upy',
  'axqolfdg64ck5t93nvwi.jpg',
  'b6ayx3oz4i1kdh8c0j5p.jpg',
  'bw980vo5htsyiezufcn3.jpg',
  'bxw1a9jumn3e76vh4ito.jpg',
  'c9udseoln5z4fjvh2btr.jpg',
  'cqde53tzrmhwkf24ly6s.jpg',
  'csdjeo87ay5up0iw96n2.jpeg',
  'd9zxur0gqoslafb6m8hj.jpg',
  'dbeqivl9wzs3j4g87xt1.jpg',
  'declbm759i2f6hxu3jyr.jpg',
  'dxfbkujpryai7gc48hn5.jpg',
  'e3vf0tsy8kjzqmrgwoxp.jpg',
  'e6nmp2qr130vyuz7jdig.jpg',
  'e6yg31j8dauvb0p45qc7.jpg',
  'e98phfjcsl4wnvdxmt6a.jpg',
  'egpcfk3d9yamb12j74nh.jpg',
  'fa7ilydou0zj31xmsn8g.jpeg',
  'fspzw9rx123nygbc6ami.jpg',
  'fvleunh07psrw364mbi2.jpeg',
  'g2uoevpkzwistc4qh07f.jpg',
  'ge08w9l7x5onz6qfrhkj.jpeg',
  'hp2t7rgalxmsfkjbiwdq.jpg',
  'hu4ect5i6k07oyxf3pr2.jpeg',
  'iglmoas4t53vhed0x927.jpg',
  'ijlrue297h6fx05btvyp.jpeg',
  'in4cmat02gsljhv9b65p.jpg',
  'izjbs7gfm9a8doq02vyk.jpg',
  'j3ni5zq1v69ko4gchu0e.jpeg',
  'j6duo5xqmrl0ab2gz7s9.jpg',
  'jh7f0ezbsl1o6tgpmvrk.jpg',
  'l3b7qh9yeuj016ntxfrk.jpg',
  'l6beota9v3zmupcqr8ix.jpeg',
  'l9mt2so6badehcu1gnx4.png',
  'lefp1caszunh79gd2w6q.jpg',
  'logdzr4kthi7c8yu5ew6.jpg',
  'lr19mk27vucnxfqyheo0.jpg',
  'lrpoxjw7k5cnae89ubt2.jpg',
  'm2hiyzb80sn1td5w4e9v.jpg',
  'm2j37l86f1yck40ovxwa.jpg',
  'mcn7xt650yeu2f4arpzq.jpg',
  'n7gal9t8iuz1e5hvsd3m.jpg',
  'nj6f25icsh9kbxl0v1at.jpeg',
  'oiu0xbkhvc27n68qg1rt.jpg',
  'oqb8t7fjpcx6hl5zdevr.jpg',
  'or7v06yb9nz83upxq4fm.jpg',
  'p2h86mvrny3954aq07gs.jpg',
  'p4vm39oxj6g0eczlt2y8.png',
  'ps65jizaocn2v8yhkdtx.jpg',
  'q4567wmfxd0u2ia91rly.jpg',
  'r7ahyjc1wz9bso0fit6x.jpg',
  'r98104olkhpungia6f3t.jpg',
  'rt10c3x5ynpo7qdhijl8.jpg',
  'ryntwma4b2dxj59zgqs8.jpeg',
  's56xoqvhlp24ga9wun8z.jpg',
  'si85xmdhau6t9ejl7npf.jpg',
  'sotn9lag0kxzv83fu24p.jpg',
  'sy1tzuavxci4no79h5f8.jpeg',
  't60w9yx5hrvi2ck4labo.jpg',
  'teswg8i560b1mpd49nh2.jpg',
  'twpr5a2x6yojznl91vbe.jpg',
  'u169ozimv08327hktgs5.jpg',
  'uw9av4m1z0rqfjdit3lp.jpg',
  'uxlb09h8om7v6rkngept.jpg',
  'v3hc064rx5yikjqdsag8.jpg',
  'vj47c28bzyi9a0rqsotw.jpg',
  'vromzhjk39fadxiw15ln.jpeg',
  'w6cyz34in0guol5vfdka.jpg',
  'x5drfp1mhjzkgcw924l0.jpg',
  'xmri19w520fcsy6jhtp8.jpg',
  'xvjaiq6pgokz8fd0mrbw.jpg',
  'ydv0qhstwgieo5mbzcrf.jpg',
  'z3xp5migr9as1td8qhkf.jpg',
  'zg8i02eyvcuf76d3qb45.jpg',
  'zkldxhoney9g4q3180tf.jpg']}

In [23]:
# ls_sku.remove('sampoerna a mild')

In [43]:
ls_sku

['sampoerna a mild',
 'gudang garam filter',
 'djarum super',
 'indomie kaldu ayam',
 'indomie kari ayam',
 'indomie ayam special',
 'indomie soto mie',
 'kapal api kopi bubuk',
 'abc kopi susu',
 'torabika duo']

In [41]:
df_dict = {}
for sku in ls_sku:
    df = pd.DataFrame(json_dict[sku])
    df['col_name'] = df[sku]
    df[sku] = 1
#     ls_sku.remove(sku)
    for ex_sku in [x for x in ls_sku if x != sku]:
        df[ex_sku] = 0
    df_dict[sku]=df

In [42]:
df_dict['sampoerna a mild']

,sampoerna a mild,col_name,gudang garam filter,djarum super,indomie kaldu ayam,indomie kari ayam,indomie ayam special,indomie soto mie,kapal api kopi bubuk,abc kopi susu,torabika duo
0,1,0iumangs8dz4yj765wop.jpeg,0,0,0,0,0,0,0,0,0
1,1,1byg08l5v39d4hrj7ike.jpg,0,0,0,0,0,0,0,0,0
2,1,2a9stjoqmzkpfxcdyge3.jpg,0,0,0,0,0,0,0,0,0
3,1,2gunsd6vjr8xfi4tble9.jpeg,0,0,0,0,0,0,0,0,0
4,1,2y4ugp036ra9dl1q5o7z.jpeg,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
92,1,xvjaiq6pgokz8fd0mrbw.jpg,0,0,0,0,0,0,0,0,0
93,1,ydv0qhstwgieo5mbzcrf.jpg,0,0,0,0,0,0,0,0,0
94,1,z3xp5migr9as1td8qhkf.jpg,0,0,0,0,0,0,0,0,0
95,1,zg8i02eyvcuf76d3qb45.jpg,0,0,0,0,0,0,0,0,0
96,1,zkldxhoney9g4q3180tf.jpg,0,0,0,0,0,0,0,0,0

In [45]:
for i, sku in enumerate(ls_sku):
    print(i,sku)
    print('')
    print(df_dict[sku])

0 sampoerna a mild

    sampoerna a mild                   col_name  gudang garam filter  \
0                  1  0iumangs8dz4yj765wop.jpeg                    0
1                  1   1byg08l5v39d4hrj7ike.jpg                    0
2                  1   2a9stjoqmzkpfxcdyge3.jpg                    0
3                  1  2gunsd6vjr8xfi4tble9.jpeg                    0
4                  1  2y4ugp036ra9dl1q5o7z.jpeg                    0
..               ...                        ...                  ...
92                 1   xvjaiq6pgokz8fd0mrbw.jpg                    0
93                 1   ydv0qhstwgieo5mbzcrf.jpg                    0
94                 1   z3xp5migr9as1td8qhkf.jpg                    0
95                 1   zg8i02eyvcuf76d3qb45.jpg                    0
96                 1   zkldxhoney9g4q3180tf.jpg                    0

    djarum super  indomie kaldu ayam  indomie kari ayam  indomie ayam special  \
0              0                   0                  0                     0
1              0                   0                  0                     0
2              0                   0                  0                     0
3              0                   0                  0                     0
4              0                   0                  0                     0
..           ...                 ...                ...                   ...
92             0                   0                  0                     0
93             0                   0                  0                     0
94             0                   0                  0                     0
95             0                   0                  0                     0
96             0                   0                  0                     0

    indomie soto mie  kapal api kopi bubuk  abc kopi susu  torabika duo
0                  0                     0              0             0
1                  0                     0              0             0
2                  0                     0              0             0
3                  0                     0              0             0
4                  0                     0              0             0
..               ...                   ...            ...           ...
92                 0                     0              0             0
93                 0                     0              0             0
94                 0                     0              0             0
95                 0                     0              0             0
96                 0                     0              0             0

[97 rows x 11 columns]
1 gudang garam filter

     gudang garam filter                   col_name  sampoerna a mild  \
0                      1   0f5nyz48b6wumlapvijo.jpg                 0
1                      1   0o7g6a15csrxkpezuq8w.jpg                 0
2                      1  0pi5bw81kdvzjhs769xf.jpeg                 0
3                      1   0vy6rtj2ua1poqi5k8d3.jpg                 0
4                      1   1frmacujdsk0xbzpi92g.jpg                 0
..                   ...                        ...               ...
130                    1   yq34lmfte0kvjph2i5rd.jpg                 0
131                    1   ytcfug0hjs8pi17bwl2r.jpg                 0
132                    1   z7ylpatmgver294s08q6.jpg                 0
133                    1   z8375v4bqx1ycs6doihj.jpg                 0
134                    1   zo1pyn9eq2xfavbtjd8l.jpg                 0

     djarum super  indomie kaldu ayam  indomie kari ayam  \
0               0                   0                  0
1               0                   0                  0
2               0                   0                  0
3               0                   0                  0
4               0                   0                  0
..            ...                 ...                ...
130             0                   0                  0
131             0                   0                  0
132             0                   0                  0
133             0                   0                  0
134             0                   0                  0

     indomie ayam special  indomie soto mie  kapal api kopi bubuk  \
0                       0                 0                     0
1                       0                 0                     0
2                       0                 0                     0
3                       0                 0                     0
4                       0                 0                     0
..                    ...               ...                   ...
130                     0                 0                     0
131                     0                 0                     0
132                     0                 0                     0
133                     0                 0                     0
134                     0                 0                     0

     abc kopi susu  torabika duo
0                0             0
1                0             0
2                0             0
3                0             0
4                0             0
..             ...           ...
130              0             0
131              0             0
132              0             0
133              0             0
134              0             0

[135 rows x 11 columns]
2 djarum super

    djarum super                   col_name  sampoerna a mild  \
0              1   1dvo4sbyepa278ig36z9.jpg                 0
1              1   1kuvawtpre2qn9i5bd7y.jpg                 0
2              1   1w80dvgy4rnbkh697qzs.jpg                 0
3              1   1xnzjef9gq0ml8wahosk.jpg                 0
4              1  2mixoue4975cqg3rp8sv.jpeg                 0
..           ...                        ...               ...
92             1   xbtam4n0s76cy2vzi13k.jpg                 0
93             1  xdblv6wkfe4izpon3s51.jpeg                 0
94             1   xw14rahfj29tcv357boq.jpg                 0
95             1  zwjnya905q8d67o1ftx3.jpeg                 0
96             1   zx38cfp5hymta7duqv4b.jpg                 0

    gudang garam filter  indomie kaldu ayam  indomie kari ayam  \
0                     0                   0                  0
1                     0                   0                  0
2                     0                   0                  0
3                     0                   0                  0
4                     0                   0                  0
..                  ...                 ...                ...
92                    0                   0                  0
93                    0                   0                  0
94                    0                   0                  0
95                    0                   0                  0
96                    0                   0                  0

    indomie ayam special  indomie soto mie  kapal api kopi bubuk  \
0                      0                 0                     0
1                      0                 0                     0
2                      0                 0                     0
3                      0                 0                     0
4                      0                 0                     0
..                   ...               ...                   ...
92                     0                 0                     0
93                     0                 0                     0
94                     0                 0                     0
95                     0                 0                     0
96                     0                 0                     0

    abc kopi susu  torabika duo
0               0             0
1               0             0
2               0             0
3               0             0
4               0             0
..            ...           ...
92              0             0
93              0             0
94              0             0
95              0             0
96              0             0

[97 rows x 11 columns]
3 indomie kaldu ayam

    indomie kaldu ayam                   col_name  sampoerna a mild  \
0                    1   0erqgjhxlbitf1ysz974.png                 0
1                    1   0tmwycu6xnbv3dfqo4i9.jpg                 0
2                    1       0zqahpsy8mt6bdku9jv2                 0
3                    1   1i0mf2kbtqp36ge94jnl.jpg                 0
4                    1   4izt3h6bmgop8xequcs5.jpg                 0
..                 ...                        ...               ...
78                   1  yvleph7jqor8c2sd310a.jpeg                 0
79                   1  yx1o83jr4ldfkpc59iw2.jpeg                 0
80                   1  zchu2xe8rb3mv674wo0l.jpeg                 0
81                   1   zg0jyc8dq3ftpk196u4v.jpg                 0
82                   1  zj3l2grxfpdnk6w1tua9.jpeg                 0

    gudang garam filter  djarum super  indomie kari ayam  \
0                     0             0                  0
1                     0             0                  0
2                     0             0                  0
3                     0             0                  0
4                     0             0                  0
..                  ...           ...                ...
78                    0             0                  0
79                    0             0                  0
80                    0             0                  0
81                    0             0                  0
82                    0             0                  0

    indomie ayam special  indomie soto mie  kapal api kopi bubuk  \
0                      0                 0                     0
1                      0                 0                     0
2                      0                 0                     0
3                      0                 0                     0
4                      0                 0                     0
..                   ...               ...                   ...
78                     0                 0                     0
79                     0                 0                     0
80                     0                 0                     0
81                     0                 0                     0
82                     0                 0                     0

    abc kopi susu  torabika duo
0               0             0
1               0             0
2               0             0
3               0             0
4               0             0
..            ...           ...
78              0             0
79              0             0
80              0             0
81              0             0
82              0             0

[83 rows x 11 columns]
4 indomie kari ayam

     indomie kari ayam                   col_name  sampoerna a mild  \
0                    1   0zxnpahbriy4167egsfo.jpg                 0
1                    1   2cxrmk4blws50je6dyof.jpg                 0
2                    1  2xqm1869b7k0jcrzpdog.jpeg                 0
3                    1   3dejx4hfmcv79lnp0wka.jpg                 0
4                    1   3ke0pimvyzgfh72xo6ab.jpg                 0
..                 ...                        ...               ...
98                   1   yw9t5g76fm132qaiolxe.png                 0
99                   1   zbrq89sguclmxkw06dv4.jpg                 0
100                  1   zijgawhxf03e81p56ndq.jpg                 0
101                  1  znxrjw0uto53lg4kade8.jpeg                 0
102                  1   zw5u47yio1mnvf9b6trj.jpg                 0

     gudang garam filter  djarum super  indomie kaldu ayam  \
0                      0             0                   0
1                      0             0                   0
2                      0             0                   0
3                      0             0                   0
4                      0             0                   0
..                   ...           ...                 ...
98                     0             0                   0
99                     0             0                   0
100                    0             0                   0
101                    0             0                   0
102                    0             0                   0

     indomie ayam special  indomie soto mie  kapal api kopi bubuk  \
0                       0                 0                     0
1                       0                 0                     0
2                       0                 0                     0
3                       0                 0                     0
4                       0                 0                     0
..                    ...               ...                   ...
98                      0                 0                     0
99                      0                 0                     0
100                     0                 0                     0
101                     0                 0                     0
102                     0                 0                     0

     abc kopi susu  torabika duo
0                0             0
1                0             0
2                0             0
3                0             0
4                0             0
..             ...           ...
98               0             0
99               0             0
100              0             0
101              0             0
102              0             0

[103 rows x 11 columns]
5 indomie ayam special

    indomie ayam special                  col_name  sampoerna a mild  \
0                      1  0f8w1ial6zcro9venypq.jpg                 0
1                      1  0f9vrb4mjdq3nwltg7ek.jpg                 0
2                      1  1bf7aknmqh5wtg9zxiuv.jpg                 0
3                      1  1j53rnxc7fpm2utk09qw.jpg                 0
4                      1  2k78tflj4prbuhc6yxz3.jpg                 0
..                   ...                       ...               ...
95                     1  yrwsde2vqu7tph45ajcb.jpg                 0
96                     1  z1qexsl596ka028ouhdg.jpg                 0
97                     1  z1rpt7gq0xhn3c5y6k49.jpg                 0
98                     1  z5m2vlc39aq48sfiepbh.jpg                 0
99                     1  zv5wfniclgeqxp0ykjh9.jpg                 0

    gudang garam filter  djarum super  indomie kaldu ayam  indomie kari ayam  \
0                     0             0                   0                  0
1                     0             0                   0                  0
2                     0             0                   0                  0
3                     0             0                   0                  0
4                     0             0                   0                  0
..                  ...           ...                 ...                ...
95                    0             0                   0                  0
96                    0             0                   0                  0
97                    0             0                   0                  0
98                    0             0                   0                  0
99                    0             0                   0                  0

    indomie soto mie  kapal api kopi bubuk  abc kopi susu  torabika duo
0                  0                     0              0             0
1                  0                     0              0             0
2                  0                     0              0             0
3                  0                     0              0             0
4                  0                     0              0             0
..               ...                   ...            ...           ...
95                 0                     0              0             0
96                 0                     0              0             0
97                 0                     0              0             0
98                 0                     0              0             0
99                 0                     0              0             0

[100 rows x 11 columns]
6 indomie soto mie

    indomie soto mie                   col_name  sampoerna a mild  \
0                  1   0j2m1tkpxoeyqs9f847d.jpg                 0
1                  1  0jrvkifwl8oc7t1bxm9u.jpeg                 0
2                  1   0lucmgpn7zjaevi21o45.jpg                 0
3                  1   0ngpyv783bzxuhwc6s25.jpg                 0
4                  1   1am3lcxtzo5v4dgi9qhe.jpg                 0
..               ...                        ...               ...
95                 1   zfw6qket3jml8a15no7i.jpg                 0
96                 1   zi4opvx6dajf795lebry.jpg                 0
97                 1  zo23msvx1yhucnbl8wgi.jpeg                 0
98                 1   zpn7awrql3eyki0jdhs4.jpg                 0
99                 1   zs2fpukqh6vje7w3c5rn.jpg                 0

    gudang garam filter  djarum super  indomie kaldu ayam  indomie kari ayam  \
0                     0             0                   0                  0
1                     0             0                   0                  0
2                     0             0                   0                  0
3                     0             0                   0                  0
4                     0             0                   0                  0
..                  ...           ...                 ...                ...
95                    0             0                   0                  0
96                    0             0                   0                  0
97                    0             0                   0                  0
98                    0             0                   0                  0
99                    0             0                   0                  0

    indomie ayam special  kapal api kopi bubuk  abc kopi susu  torabika duo
0                      0                     0              0             0
1                      0                     0              0             0
2                      0                     0              0             0
3                      0                     0              0             0
4                      0                     0              0             0
..                   ...                   ...            ...           ...
95                     0                     0              0             0
96                     0                     0              0             0
97                     0                     0              0             0
98                     0                     0              0             0
99                     0                     0              0             0

[100 rows x 11 columns]
7 kapal api kopi bubuk

    kapal api kopi bubuk                   col_name  sampoerna a mild  \
0                      1   0jkiv2t7ousz8lecmp5w.jpg                 0
1                      1   0tl2v1cx9d4iy68jfgqa.jpg                 0
2                      1   0yac6dml3zst2pgirnk8.jpg                 0
3                      1  1npbdvsgl2q54jzeuxk0.jpeg                 0
4                      1   1ukjz36ntgyver52blhw.jpg                 0
..                   ...                        ...               ...
95                     1   xairny23qlb0wg6jpkh4.jpg                 0
96                     1   xkwcrn96y04bizsfoqem.png                 0
97                     1   xvzjcb2yhrutkp4qi091.jpg                 0
98                     1   y69lv1mx3h5orz4ubi8e.jpg                 0
99                     1   zm798y1cqi5kfs4j3ue0.jpg                 0

    gudang garam filter  djarum super  indomie kaldu ayam  indomie kari ayam  \

In [47]:
df_dict['djarum super']

,djarum super,col_name,sampoerna a mild,gudang garam filter,indomie kaldu ayam,indomie kari ayam,indomie ayam special,indomie soto mie,kapal api kopi bubuk,abc kopi susu,torabika duo
0,1,1dvo4sbyepa278ig36z9.jpg,0,0,0,0,0,0,0,0,0
1,1,1kuvawtpre2qn9i5bd7y.jpg,0,0,0,0,0,0,0,0,0
2,1,1w80dvgy4rnbkh697qzs.jpg,0,0,0,0,0,0,0,0,0
3,1,1xnzjef9gq0ml8wahosk.jpg,0,0,0,0,0,0,0,0,0
4,1,2mixoue4975cqg3rp8sv.jpeg,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
92,1,xbtam4n0s76cy2vzi13k.jpg,0,0,0,0,0,0,0,0,0
93,1,xdblv6wkfe4izpon3s51.jpeg,0,0,0,0,0,0,0,0,0
94,1,xw14rahfj29tcv357boq.jpg,0,0,0,0,0,0,0,0,0
95,1,zwjnya905q8d67o1ftx3.jpeg,0,0,0,0,0,0,0,0,0
96,1,zx38cfp5hymta7duqv4b.jpg,0,0,0,0,0,0,0,0,0

In [48]:
df_baru = pd.DataFrame()

for i, sku in enumerate(ls_sku):
    df_baru = pd.concat([df_baru,df_dict[sku]])

df_baru = df_baru.reset_index(drop=True)

In [49]:
df_baru

,sampoerna a mild,col_name,gudang garam filter,djarum super,indomie kaldu ayam,indomie kari ayam,indomie ayam special,indomie soto mie,kapal api kopi bubuk,abc kopi susu,torabika duo
0,1,0iumangs8dz4yj765wop.jpeg,0,0,0,0,0,0,0,0,0
1,1,1byg08l5v39d4hrj7ike.jpg,0,0,0,0,0,0,0,0,0
2,1,2a9stjoqmzkpfxcdyge3.jpg,0,0,0,0,0,0,0,0,0
3,1,2gunsd6vjr8xfi4tble9.jpeg,0,0,0,0,0,0,0,0,0
4,1,2y4ugp036ra9dl1q5o7z.jpeg,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1009,0,yctgpbf8654hxkniv2uq.jpg,0,0,0,0,0,0,0,0,1
1010,0,yrk2736dipxqmjauw8sl.jpeg,0,0,0,0,0,0,0,0,1
1011,0,z0aojtwu1qb3vmdkg6ir.jpg,0,0,0,0,0,0,0,0,1
1012,0,zcdo1efyhk437sb86r5t.jpg,0,0,0,0,0,0,0,0,1
1013,0,zw1racidu4y5pblf6sq8.jpg,0,0,0,0,0,0,0,0,1

In [50]:
df_baru.to_csv("data.csv",index=False)